name: Update GTA Showrooms to Supabase

on:
  schedule:
    - cron: '0 9 * * 4'
  workflow_dispatch:

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

jobs:
  scrape-and-push-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install cheerio axios @supabase/supabase-js dotenv

      - name: Run Scraper and Upload
        run: node get-weekly-update.js
